[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "labelsom"
requires-python = ">=3.9"
dynamic = ["dependencies"]
version = "0.0.1"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.pytest.ini_options]
pythonpath = "src"
